In [1]:
import pandas as pd

In [3]:
db=pd.read_csv("50_Startups.csv")

In [4]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [5]:
db.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [7]:
X = db[['R&D Spend', 'Administration', 'Marketing Spend']]

In [8]:
y = db["Profit"]

In [9]:
state = db["State"]

In [10]:
state_fi =pd.get_dummies(state ,drop_first=True)

In [11]:
state_fi

Florida  New York
0         0         1
1         0         0
2         1         0
3         0         1
4         1         0
5         0         1
6         0         0
7         1         0
8         0         1
9         0         0
10        1         0
11        0         0
12        1         0
13        0         0
14        1         0
15        0         1
16        0         0
17        0         1
18        1         0
19        0         1
20        0         0
21        0         1
22        1         0
23        1         0
24        0         1
25        0         0
26        1         0
27        0         1
28        1         0
29        0         1
30        1         0
31        0         1
32        0         0
33        1         0
34        0         0
35        0         1
36        1         0
37        0         0
38        0         1
39        0         0
40        0         0
41        1         0
42        0         0
43        0         1
44        0         0
45        0         1
46        1         0
47        0         0
48        0         1
49        0         0

In [12]:
db_fi = pd.concat([state_fi,X],axis = 1)

In [13]:
db_fi

Florida  New York  R&D Spend  Administration  Marketing Spend
0         0         1  165349.20       136897.80        471784.10
1         0         0  162597.70       151377.59        443898.53
2         1         0  153441.51       101145.55        407934.54
3         0         1  144372.41       118671.85        383199.62
4         1         0  142107.34        91391.77        366168.42
5         0         1  131876.90        99814.71        362861.36
6         0         0  134615.46       147198.87        127716.82
7         1         0  130298.13       145530.06        323876.68
8         0         1  120542.52       148718.95        311613.29
9         0         0  123334.88       108679.17        304981.62
10        1         0  101913.08       110594.11        229160.95
11        0         0  100671.96        91790.61        249744.55
12        1         0   93863.75       127320.38        249839.44
13        0         0   91992.39       135495.07        252664.93
14        1         0  119943.24       156547.42        256512.92
15        0         1  114523.61       122616.84        261776.23
16        0         0   78013.11       121597.55        264346.06
17        0         1   94657.16       145077.58        282574.31
18        1         0   91749.16       114175.79        294919.57
19        0         1   86419.70       153514.11             0.00
20        0         0   76253.86       113867.30        298664.47
21        0         1   78389.47       153773.43        299737.29
22        1         0   73994.56       122782.75        303319.26
23        1         0   67532.53       105751.03        304768.73
24        0         1   77044.01        99281.34        140574.81
25        0         0   64664.71       139553.16        137962.62
26        1         0   75328.87       144135.98        134050.07
27        0         1   72107.60       127864.55        353183.81
28        1         0   66051.52       182645.56        118148.20
29        0         1   65605.48       153032.06        107138.38
30        1         0   61994.48       115641.28         91131.24
31        0         1   61136.38       152701.92         88218.23
32        0         0   63408.86       129219.61         46085.25
33        1         0   55493.95       103057.49        214634.81
34        0         0   46426.07       157693.92        210797.67
35        0         1   46014.02        85047.44        205517.64
36        1         0   28663.76       127056.21        201126.82
37        0         0   44069.95        51283.14        197029.42
38        0         1   20229.59        65947.93        185265.10
39        0         0   38558.51        82982.09        174999.30
40        0         0   28754.33       118546.05        172795.67
41        1         0   27892.92        84710.77        164470.71
42        0         0   23640.93        96189.63        148001.11
43        0         1   15505.73       127382.30         35534.17
44        0         0   22177.74       154806.14         28334.72
45        0         1    1000.23       124153.04          1903.93
46        1         0    1315.46       115816.21        297114.46
47        0         0       0.00       135426.92             0.00
48        0         1     542.05        51743.15             0.00
49        0         0       0.00       116983.80         45173.06

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
db_fi_train,db_fi_test,y_train,y_test = train_test_split(db_fi,y,test_size=0.20,random_state=42)

In [17]:
db_fi_train.info

<bound method DataFrame.info of     Florida  New York  R&D Spend  Administration  Marketing Spend
12        1         0   93863.75       127320.38        249839.44
4         1         0  142107.34        91391.77        366168.42
37        0         0   44069.95        51283.14        197029.42
8         0         1  120542.52       148718.95        311613.29
3         0         1  144372.41       118671.85        383199.62
6         0         0  134615.46       147198.87        127716.82
41        1         0   27892.92        84710.77        164470.71
46        1         0    1315.46       115816.21        297114.46
47        0         0       0.00       135426.92             0.00
15        0         1  114523.61       122616.84        261776.23
9         0         0  123334.88       108679.17        304981.62
16        0         0   78013.11       121597.55        264346.06
24        0         1   77044.01        99281.34        140574.81
34        0         0   46426.07       15769

In [19]:
db_fi_train=db_fi_train.values#to convert into pandas

In [20]:
db_fi_train.reshape(-1,1)#to convert into 2D

array([[1.0000000e+00],
       [0.0000000e+00],
       [9.3863750e+04],
       [1.2732038e+05],
       [2.4983944e+05],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.4210734e+05],
       [9.1391770e+04],
       [3.6616842e+05],
       [0.0000000e+00],
       [0.0000000e+00],
       [4.4069950e+04],
       [5.1283140e+04],
       [1.9702942e+05],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.2054252e+05],
       [1.4871895e+05],
       [3.1161329e+05],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.4437241e+05],
       [1.1867185e+05],
       [3.8319962e+05],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.3461546e+05],
       [1.4719887e+05],
       [1.2771682e+05],
       [1.0000000e+00],
       [0.0000000e+00],
       [2.7892920e+04],
       [8.4710770e+04],
       [1.6447071e+05],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.3154600e+03],
       [1.1581621e+05],
       [2.9711446e+05],
       [0.0000000e+00],
       [0.000000

In [21]:
type(db_fi_train)

numpy.ndarray

In [22]:
db_fi_train.shape

(40, 5)

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
model = LinearRegression()

In [25]:
model.fit(db_fi_train,y_train)

LinearRegression()

In [26]:
model.coef_

array([ 9.38793006e+02,  6.98775997e+00,  8.05630064e-01, -6.87878823e-02,
        2.98554429e-02])

In [27]:
import joblib

In [28]:
joblib.dump(model,"startups.pk1")

['startups.pk1']

In [ ]:
db_fi_train.shape

In [33]:
y_pred=model.predict(db_fi_test)

In [34]:
y_pred

array([126362.87908252,  84608.45383643,  99677.49425155,  46357.46068582,
       128750.48288497,  50912.41741905, 109741.350327  , 100643.24281644,
        97599.275746  , 113097.42524437])